# Generated by Django 4.2.2 on 2023-07-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_receiver_message_recipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
